### ISSUE TITLE
APP会闪退

### ISSUE THREAD

**Issue by DGbankClouds** [ys1231/appproxy#13]
0.0.8版本，打开APP后，需要停顿等待一短时间才能正常点击菜单按钮。如果打开APP马上点击任一菜单按钮的话，会卡住然后APP闪退

**Comment by ys1231** [comment]
什么手机型号，和系统版本？

**Comment by DGbankClouds** [comment]
一加9Pro，ColorOS13.1

**Comment by ys1231** [comment]
单线程还是有点勉强，有时间再优化。

**Comment by ys1231** [comment]
已经优化完成.
