### ISSUE TITLE
抓包的问题

### ISSUE THREAD

**Issue by huaqqdu** [ys1231/appproxy#14]
大佬，目前我用这个工具很不错，想请问一下，如果想实现抓https包实现重定向，是需要自己实现解析流量然后判断https请求然后再返回自己的证书(已导入证书到安卓系统)，这样才能解析https吗，还是这软件其实已经实现

**Comment by ys1231** [comment]
appproxy 只做数据转发. 安装证书使用另一个 [Move Certificate](https://github.com/ys1231/MoveCertificate)
