### ISSUE TITLE
配置页面刷新APP列表时加载缓慢

### ISSUE THREAD

**Issue by nhqqxs** [ys1231/appproxy#16]
在配置页面下拉刷新以重新获取APP列表时差不多要转圈圈3秒钟
![图片](https://github.com/user-attachments/assets/ed34d31a-391e-43cf-a55e-ac1249826480)

**Comment by ys1231** [comment]
可以考虑监听安装卸载，最近比较忙，有时间再优化。

**Comment by ys1231** [comment]
暂时没时间改,等我受不了了 再改.有需要可以重新提.
