### ISSUE TITLE
搜索功能

### ISSUE THREAD

**Issue by TopMaps** [ys1231/appproxy#3]
app太多分应用代理不方便，希望可以添加一个搜索功能快速定位勾选！

**Comment by TopMaps** [comment]
另一个显示问题：Vpn开启状态，appproxy切掉后台，重进入后，代理开启状态显示关闭，实际上vpn依旧开着。

**Comment by ys1231** [comment]
搜索功能已经添加,但是状态的话,由于使用第三方库实现的转发,不能实时监控状态,就干脆不实现了,可以从状态栏回到app这样是正常的,不影响使用,暂时先不管它.
