### ISSUE TITLE
抓包地址应该怎么填

### ISSUE THREAD

**Issue by yisar** [ys1231/appproxy#4]
是填写我自己的服务器地址，还是填写本地地址，端口填什么，完全填不对

**Comment by ys1231** [comment]
哔哩哔哩 可以帮助你。

**Comment by yisar** [comment]
完全不懂，可以来个视频地址吗，因为光秃秃的真不知道填啥能填对

**Comment by ys1231** [comment]
抓包总是有抓包工具，抓包工具所在的ip地址和监听的端口就是你需要的填写的，如果这个都不懂说明你需要学习。

**Comment by yisar** [comment]
按照我的理解，比如charles会自动生成一个本地ip和端口8888，然后手机的dns代理填这个ip和端口

你这个是相当于手动dns功能吗？还是相当于charles？
这是我的疑问

1. 如果是相当于手动dns功能，那么这里的ip和端口是填写charles的吗？
2. 如果不是，那这里的ip和端口是填写某一个server的吗？
3. 理想状态下，应该是不需要填地址的，直接开一个server，类似小黄鸟或clash，自己抓包自己

你能回答这三个问题就行，别说学习不学习的，这不是个技术问题，只是一个readme问题

**Comment by yisar** [comment]
时隔一年再来回复一下，之前被无情关闭了
这个软件类似手机的dns代理功能，只负责流量转发，通常是转发到其他抓包工具上，比如fiddler之类的

和小黄鸟，抓包精灵之类的完全不同，通常这类抓包工具是安卓端开一个server，自己转发自己，这样就可以看到抓包的内容了

由于之前没有看代码，想要issue先问一问，结果被博主一句话关闭issue，所以特此来说明一下
