### ISSUE TITLE
大佬，从tun2socks过来的

### ISSUE THREAD

**Issue by fk0crypto0proker** [ys1231/appproxy#5]
https://github.com/xjasonlyu/tun2socks/issues/123
从这个问题过来的，请问你这个怎么解决的？
![image](https://github.com/user-attachments/assets/b776d14d-5357-47fe-8333-e01f5e676dd8)

**Comment by fk0crypto0proker** [comment]
![image](https://github.com/user-attachments/assets/5ad132fa-2dee-4d0b-809a-f5a8da254614)

**Comment by ys1231** [comment]
看我代码。
