### ISSUE TITLE
能不能提一个小建议啊

### ISSUE THREAD

**Issue by soshunte** [ys1231/appproxy#8]
能不能提一个小建议啊，目前虽然是勾选d代理了，但是很多app还是会跑出来很多 大厂的 流量，会有很多其他的无关竟要的域名流量跑进来 能不能像SwitchyOmega 格式引用过滤掉这些，目前SwitchyOmega这个比较全的，引用SwitchyOmega这种格式比较方便入*baidu*，比如直接在你的github来加载这些,，用户也可以自定义来加载自己的过滤字典. 目前我收集了很多，需要的话请留言

**Comment by ys1231** [comment]
appproxy 的定位是转发流量到服务器,对于你说的,貌似对于此软件的功能定位不符合.

**Comment by soshunte** [comment]
转发流量的时候有的app会有很多qq的aliyun的呀 ，baidu的谷歌的流量进去，当然是分析流量，小建议就是 可以设置黑名单  用户可以自定义去设置的（不设置的情况下流量杂乱  设置的情况下更直观清晰），看起来并不影响此软件的定位 相反更便捷方便，

**Comment by ys1231** [comment]
作为一个代理工具，把所有流量转发才是主业，过滤这种事更应该交给burp这种专业的工具去做。

**Comment by soshunte** [comment]
正如你所说，转发流量是主业，但是分析流量的时候突然跑出来一大堆干扰的流量会降低这个软件的便捷.就好比 ，你会设置配置功能 勾选的app打开就能代理，不勾选就不用代理，就是一样 有些域名会干扰流量正常分析.如果使用者能够自定义那些流量不需要代理，可以添加或者删除这些域名的功能 相反你的这款软件是最便捷 实用的

**Comment by ys1231** [comment]
app难道就没有这些流量了，你可以自己fork一个改。
