### ISSUE TITLE
mitmproxy正常, fiddler出问题

### ISSUE THREAD

**Issue by GitCourser** [ys1231/appproxy#9]
遇到个奇怪的问题
电脑上装的 fiddler 和 mitmproxy, 手机上两个软件的证书都安装了, 手机上用wifi设置全局代理时都能用
但用 appproxy 时, 比如指定手机浏览器后, 连 mitmproxy 时正常, 连 fiddler 时就提示证书错误

**Comment by ys1231** [comment]
fiddler 的证书有效期是多久,太长的不行,可以先用系统代理排除一下是否由 appproxy 导致的问题,事实上我很明确appproxy 不会导致证书错误.

**Comment by GitCourser** [comment]
那就怪了,实际上是mitm的证书时间更长
对了,昨天忘记说环境了

电脑: win10
手机: miui12.5(android 11)
fiddler: v5.0.20211.51073
mitmproxy: v9.0.1

![image](https://github.com/user-attachments/assets/b0ce172b-58ea-47ff-bfc7-776cd3293b39)
![image](https://github.com/user-attachments/assets/f74b48c3-8185-44c7-8e6a-51715d749e6d)

wlan设置全局代理时正常,但用 appproxy 时, 浏览器访问baidu.com如下,按继续也不会正常显示网页
![image](https://github.com/user-attachments/assets/6930f0f3-35f3-4421-bdb4-8fa7eda2ec39)

**Comment by ys1231** [comment]
别说 fiddler 只有在初学的时候用过,好多年了,有时间试试.

**Comment by ys1231** [comment]
fiddler 确实有问题, 试了一下其他代理软件一样的结果, 暂时不考虑解决这个问题, 几乎不会去用,你有兴趣可以研究一下.
